# 1. Define the IngressClass so Kubernetes knows "aralez" is a valid controller
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: aralez
  namespace: upstreams
spec:
  controller: aralez.proxy/ingress-controller
